### ISSUE TITLE
Add warning that this project is under development and submitted ideas are getting deleted from time to time

### ISSUE THREAD

**Issue by jdohm** [jdohm/openidea#18]
Add a text to the new Idea popup created inside Idea.js which states "something like "this project is under development, your idea could be deleted at any time".

Also look into the size of the popup since the correct placement on the map is at the moment calculated without checking the actual popup size

**Comment by sumitk63** [comment]
Hey jdohm i would like to work on this. Can you please describe what to do in bit more details.

**Comment by jdohm** [comment]
Hey @sumitk63 I updated the description. Your very welcome to work on this, please keep in mind this is still in a really early development state and not jet decided how far it will go.
