### ISSUE TITLE
Change Idea location

### ISSUE THREAD

**Issue by xPeedx** [jdohm/openidea#37]
Maybe it shoud be possible to change the place of a Idea when the project moves to amother place. Only for the person who created the Idea.

**Comment by jdohm** [comment]
I believe any idea is only as strong as it's community. If one user (even though he planted the seed) could change anything without the others who helped grow that idea, I'm not sure that's good.  However, as the places can and will change (for example an idea was born in a garage but now moves to its own building) some way of changing the location of an idea will be necessary in the future. 

For the near future a support request will be sufficient (and a change of the database at admin level) but if this project growth it will need a good automated way to change idea locations.

**Comment by jdohm** [comment]
This can be done via a support request for now.
This could be automated if need arises.
