### ISSUE TITLE
Classification

### ISSUE THREAD

**Issue by xPeedx** [jdohm/openidea#41]
Only some Ideas:
Starter
Rocket Starter
Big fucking Rocket
Visionary 
Shining Star
FreeIdea
OpenIdea
Bought it to the moon
Left the moon behind
Leaving Earth or Atmosphere
Nature Science
Terra forming
Space Idea

**Comment by jdohm** [comment]
@xPeedx 
Could you be more specific? 
There are "classes" called topics and needed skills. 

Is your issue to implement some sort of badges for often upvoted ideas? If so, what do you have in mind, when it comes to displaying these badges/achievements?

**Comment by xPeedx** [comment]
It was only a Brainstorm. I know that there are some things mixed. I or better said we have to think about...

**Comment by xPeedx** [comment]
Yes I wanted to implement some Badges but as said above we shoud think about and I mixed some things together in my Brainstorm...

**Comment by jdohm** [comment]
Please let us discuss things like that on our matrix group and only create an issue when there is an issue, an suggestion for a new feature or a suggestion for an improvement :)

I'm closing this for now, your welcome to brainstorm or discuss this with me on matrix. Once a clear issue/improvement/feature request arises please feel free to create a new issue here on github :)
