### ISSUE TITLE
Other Colour for the OpenIdea Idea

### ISSUE THREAD

**Issue by xPeedx** [jdohm/openidea#43]
It woud be great if the Idea of OpenIdea could get another Colour than all other Ideas.

**Comment by jdohm** [comment]
I understand your concern is, that new users don't know where to start.
b5448ed implements a redirect to your OpenIdea idea for new users and an info button to go back to that idea at any point.
This issue isn't closed for now, id like to add a extra welcome page which explains our project more in detail and lets the user know that clicking on the info button will bring back that menu.
![image](https://user-images.githubusercontent.com/9203094/111090815-4d32d200-8531-11eb-8082-f30880c9fbca.png)

**Comment by jdohm** [comment]
welcome screen is now presented to new users. As of 216123d2864e11886097b18174c185693217e5b4 it also links to an explanation video. The text could need some improvements but this issue will be closed since the main issue is resolved.
